name: EKS setups 
on:
  workflow_dispatch:  

env: 
  AWS_ACCESS_KEY : ${{secrets.ACCESS_KEY}}
  AWS_SECRET_KEY: ${{secrets.SECRET_KEY}}
  AWS_BUCKET: ${{secrets.BUCKET}}
  aws_region: us-east-1
  aws_cluster: cluster_eks



jobs:
  eks_setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init 
        run: terraform init -backend-config="bucket=${{env.AWS_BUCKET}}"

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -out=planfile -input=false

      
